---
title: 'blog post 6: algorithm transparency + case law'
---
By [Sarah Gillespie](https://www.linkedin.com/in/sarahg4567/)
 
*in progress*

*This blog post is not legal advice. This blog post is just me reading through case law that I find fascinating and making my notes on it public in case anyone finds my interpretation and annotations helpful.*
 
Case briefs on United States' court rulings that create case law impact regarding algorithm transparency and public auditing of machine learning algorithms:

***

Case brief structure:

(a) Facts (name of the case and its parties, what happened factually and procedurally, and the judgment)

(b) Issues (what is in dispute)

(c) Holding (the applied rule of law)

(d) Rationale (reasons for the holding)

(e) Dicta (commentary about the decision that was not the basis for the decision)

(f) Dissent (if a valuable dissenting opinion exits, the dissent’s opinion)

(g) Party’s Arguments (each party’s opposing argument concerning the ultimate issue)

(h) Comments (personal commentary)

***

**[CHRISTIAN W. SANDVIG, et al., v. WILLIAM P. BARR, in his official capacity as Attorney General of the United States / Civil Action No. 16-1368 (JDB)](https://www.aclu.org/sites/default/files/field_document/sandvig_opinion.pdf)**

(a) **Facts**:
The plaintiffs are academic researchers who intend to test whether employment websites discriminate based on race and gender by providing false information to target websites, in violation of these websites’ terms of service. The plaintiffs are concerned that this act would violate the websites' terms of service about not providing false information. The Court did not address the researchers First Amendment right to free speech in this case, but the Court did conclude that the Computer Fraud and Abuse Act does not criminalize terms-of-service violations of consumer websites. The impact of this conclusion is that the plaintiffs' proposed research plans are not considered criminal under the Computer Fraud and Abuse Act.

[to do: add more about the procedural history of this case without getting too in the weeds of details?]

(b) **Issues**:
Whether or not it is criminal to provide false information to consumer websites, even if the websites' terms of service state that users are not permitted to provide false information to the website. The plaintiffs' specific potential criminal behavior would be to visit LinkedIn, Monster, Glassdoor, and Entelo and violate these sites' terms of service by creating accounts based on false or misleading information.

(c) **Holding**:
It is not a violation of the Computer Fraud and Abuse Act to audit an algorithm for academic research in the way the plaintiffs were intending to do.

(d) **Rationale**:
- the Court finds it concerning to allow private website owners to define what is considered criminal.
- part of the reason why it was not criminal under the Computer Fraud and Abuse Act was that the plaintiffs do not bypass an authorization gate by doing something like provide false credit card or social security numbers and instead just use the information they generated when creating tester accounts and intend to compley with payment requirements for sites that require it. Courts are currently divided on what counts on exceeding authorization access. See page 25 in [the March 2020 opinion ruling](https://www.aclu.org/sites/default/files/field_document/sandvig_opinion.pdf) for more details.
- the court did not address the First Amendment issue because it had concluded that the plaintiffs' research plans do not violate the Access Provision of the Computer Fraud and Abuse Act. The case is dismissed, which means that the researchers could not be considered guilty of violating the law by their proposed auditing.

(e) **Dicta**:

There was back-and-forth with the government arguing that the plaintiffs' testimony shows that they do not fear persecution and have already engaged in such research,  that past Computer Fraud and Abuse Act prosecutions do not establish a credible thread that the plaintiffs' proposed conduct will be prosecuted, and general government charging policy and public statements do not suggest that the academic researchers would be prosecuted for auditing algorithms for bias against protected classes. The plaintiffs' argument was that they were concerned at putting their students, who may conduct some of the algorithm auditing research, under risk of prosecution. John T. Lynch, Jr., the Chief of the
Computer Crime and Intellectual Property Section of the Criminal Division of the Department of Justice, testified at his deposition that it was not impossible for the Department to bring a Computer Fraud and Abuse Act prosecution and de minimis harm, but that he does not expect the Department to bring a prosecution. The plaintiffs argued that the "Constitution 'does not leave us at the mercy of noblesse oblige,'" quoting a different court case.

*Definitions: de minimis = avoid having the court resolve trivial problems that are not worth the judge's time; noblesse oblige = the concept that privileged people have a responsibility to act with generosity towards less privileged people*

(f) **Dissent**: no dissenting opinion published.

(g) **Party’s Arguments**: 
This was a pre-enforcement challenge, meaning that the plaintiffs and defendants were arguing about the constitutionality of the Computer Fraud and Abuse Act and website terms of service before the plaintiffs did any academic research that might violate the Computer Fraud and Abuse Act or website terms of service.

(h) **Personal commentary**:
While the plaintiffs did not ask for access to hiring algorithms' source code, they did get the "okay" to do audit testing to research if an algorithm displays bias against the protected classes of race and gender. Note that the outcome of this audit testing is limited: the researchers would find that there is or is not bias against the groups that they test, but would not be able to see specifically what training data or other problem is making the algorithm biased.

The pre-enforcement challenge was filed in 2016 and the concluding opinion was published in March 2020.

***

Other cases to do court briefs on in the future:
- add