---
title: 'Intro Python with a biology focus: practice'
---
By [Sarah Gillespie](https://www.linkedin.com/in/sarahg4567/)  
 
<br> 

### Notes

To solve these problems, read the documentation, read Stack Overflow, and Google. It's an "open book" assignment.

Celebrate error messages: errors can be annoying but it means you're creatively testing the boundaries of Python.

Include lots of comments to explain your code. It's a relief to anyone who reads your future code to have a comment to know your thought process, what the code is supposed to do, code weaknesses, and requirements for that code to run successfuly.

There isn't a "right" and "wrong" answer to each problem, per se. There are some very straightforward ways to solve these problems and some ways that are an avoidable hassle but do technically work.

Create a new Google Colab notebook to solve these practice problems. Attempt each problem on your own before asking for help. We will work together to solve these problems later, starting from wherever you got stuck. It's better to have tried and havea wrong answer than leave something blank.

<br>

### Section 1: Strings

#### 1.0 Describe a string in your own words, including some limitations of this type of data structure.

#### 1.1 Print the COVID genome.

```
# Hint: Make sure you run the below code to pull in the UCSC COVID genome into your Google Colab's stort-term memory.

pip install ucsc_genomes_downloader
from ucsc_genomes_downloader import Genome
covid = Genome("wuhCor1")

genome = covid["NC_045512v2"]
```

#### 1.2 Print the first 5 charecters in the COVID genome.

#### 1.3 Print the variable that contains the COVID test results list.

```
# The assigned list is:

COVID_test_results = ["negative", "negative", "negative", "postitive", "negative", "positive", "negative"]
```

#### 1.4 Describe a list in your own words, including some limitations of this type of data structure.

<br>

### Section 2: For-loops

#### Describe a for-loop in your own words, including the limitations of this programming tool.

#### 2.1 Pretend the month is September 2021. Use a "for" loop to print each item in the COVID test results list, one test result at a time.

#### 2.2 Pretend the month is Februrary 2020... use the for-loop you wrote above in Section 2.1, an if-statement, and a "break" statement to halt the for-loop as soon as you the loop finds a postive test result. For bonus points, include an outputted message to alert the reader of a "yikes! this is a postive test result!!!!" upon the for-loop's iteration over a positive result.

#### 2.3 Pretend the month is December 2022. Use a for-loop to iterative over all the test results. Use an if-statement to only print the result if the test has a positive result.

<br>
### Section 3: Integers

#### 3.0 Describe an integer in your own words.

#### 3.1 Simple calculation of a total

##### 3.1.1 Use Python to calculate the quantity of people who were tested for COVID. (Hint: Find the length of the COVID_test_results list)

##### 3.1.2 Write this quantity be a variable titled "total_results". You will need to use this variable later.

#### 3.2 Simple calculation of a subset
##### 3.2.1 Use Python to print the quantity of people who tested positive for COVID. (Hint: Find the length of the COVID_test_results list)
##### 3.2.2 Write this quantity as a variable titled "total_positive_results". You will need this variable later.


#### 3.3 Convert an integer to a string use the numbers above to print a sentence in the structure of "out of a total of X people, K people tested positive for COVID." For bonus points, have a print() statement that combines both the sentence, total_results variable, and total_positive_results variable. 

### Section 4: Floats

#### 4.1 Use Python to calculate a float of the ratio of people who tested postitive relative to the total number of people tested. The total_results variable and total_positive_results variable from above will be helpful here.
