---
title: 'Intro Python graphs with a biology focus: practice'
---
By [Sarah Gillespie](https://www.linkedin.com/in/sarahg4567/)  
 
<br> 

### Notes

To solve these problems, read Plotly documentation, Stack Overflow, and Google. It's an "open book" assignment.

Celebrate error messages: errors can be annoying but it means you're creatively testing the boundaries of Python.

Include excellent comments to explain your code. It's a relief to anyone who reads your future code to have a comment to know your thought process, what the code is supposed to do, code weaknesses, and requirements for that code to run successfuly.

Create a new Google Colab notebook to solve these practice problems. Attempt each problem on your own before asking for help. We will work together to solve these problems later, starting from wherever you got stuck. It's better to have tried and have a wrong answer than leave something blank.

<br>

### Section 1: Datawrangling basics

The example dataframe used in this section will be a guesstimate of the quanity of food that my cats eat each day.

#### Load in data: this section will explore different data structures. This is the building blocks of Microsoft Excel and the old-school version of the CSV files you will use in later practice problems.

```
# import pandas, the library that makes it easier to work with dataframes
import pandas as pd  
cats_lst = ["Ada Lovelace", "Quinn", "Eevee", "Cola", "Clem"]

# Calling DataFrame constructor on list  
cats_df = pd.DataFrame(cats_lst)  
print(cats_df)  

```
Comprehension question: what type of data structure is:
<br>
1. cats_df
<br>
2. cats_lst
<br>
3. the elements within the brackets? 
<br>

<div id="spoiler" style="display:none">

1. cats_df is a dataframe.
<br>
2. cats_lst is a list.
<br>
3. the elements within the brackets are strings.

There are a number of naming conventions for variables, but the default naming convention in 2023 is to use the relevant data structure as a suffix. That way it's immediately evident to someone proofreading your code that the variable is a list/constant/etc.

Additionally, you probably noticed the underscores. Python uses "snake_case" to name variables: lowercase words and an underscore to separate words. That should be your default for Python variables until we come across a new data structure called "classes" that use UpperCamelCase for class names.

</div>

<button title="Click to show answer" type="button"
   onclick="if(document.getElementById('spoiler') .style.display=='none')
              {document.getElementById('spoiler') .style.display=''}
            else{document.getElementById('spoiler') .style.display='none'}">
  Show/hide
</button>

#### Calculating summary statistics

```
import pandas as pd  
  
# Create a Dataframe from a set of lists 
cat_food_lists = {'cat': ['Ada', 'Quinn', 'Eevee', 'Cola', 'Ada', 'Quinn', 'Eevee', 'Ada', 'Quinn', 'Eevee'], 'quantity_in_grams': [310, 250, 200, 200, 295, 225, 210, 300, 230, 190], 'day': ['Sunday', 'Sunday', 'Sunday', 'Sunday', 'Monday', 'Monday', 'Monday', 'Tuesday', 'Tuesday', 'Tuesday']}  
  
# Create a DataFrame from the cat food data. This is called casting the dictionary as a dataframe.
cat_food_df = pd.DataFrame(cat_food_lists)  
  
# Print the output.  
print(cat_food_df) 

```

Communicate the cat food chomping results. 

Find and print the mean, median, minimum, and maxiumum of the "quantity_in_grams" column using pandas.

<div id="spoiler2" style="display:none">

The long way:
<br>

```
cat_food_mean = cat_food_df["quantity_in_grams"].mean()
print(cat_food_mean)

cat_food_median = cat_food_df["quantity_in_grams"].median()
print(cat_food_mean)

cat_food_min = cat_food_df["quantity_in_grams"].min()
print(cat_food_min)

cat_food_max = cat_food_df["quantity_in_grams"].max()
print(cat_food_max)

```

The short way:
<br>
```
cat_food_agg_df = cat_food_df.agg(
{
"quantity_in_grams":["mean", "median", "min", "max"]
}
)

print(cat_food_agg_df)
```

</div>

<button title="Click to show answer" type="button"
   onclick="if(document.getElementById('spoiler2') .style.display=='none')
              {document.getElementById('spoiler2') .style.display=''}
            else{document.getElementById('spoiler2') .style.display='none'}">
  Show/hide
</button>


#### Challenge question: Grouping your data into categories.
It's great that we can find the overarching summary statistics, but what if we want to comapre or discover specific day or a specific cat's data?

Use pandas' "group by" method to find the mean food consumption for each cat and for each day.

### Section 2: Graphing review and challenge

#### Use Plotly to create a scatterplot of cat food data

Create a scatterplot of cat food consumption, broken down by each cat.

<div id="spoiler3" style="display:none">

```
import plotly.express as px

fig = px.scatter(cat_food_df, y="cat", x="quantity_in_grams", color="cat")
fig.update_traces(marker_size=10)
fig.show()
```
Challenge: change something and re-run this code! What happens if you set the marker_size to 100? Your x_axis to "cat"? Your color to "quantity_in_grams"?

</div>

<button title="Click to show answer" type="button"
   onclick="if(document.getElementById('spoiler3') .style.display=='none')
              {document.getElementById('spoiler3') .style.display=''}
            else{document.getElementById('spoiler3') .style.display='none'}">
  Show/hide
</button>


#### Use Plotly and the min/max variables above to create a bar chart.

Edit the sample code below to have it automatically calculate and graph summary statistics so you don't have the manually enter the x-axis and y-axis data each time.

Hint: filter the data set, calculate variables, and paste the variables into the code below. There are many ways to reach the correct answer.

```
# An example of filtering and creating a new data frame to only keep the Ada values
ada_cat_food_df = cat_food_df[(cat_food_df.cat == "Ada")]

# A sample bar chart
fig = px.bar(x=["Ada","Quinn","Eevee", "Cola"], y=[1,3,2,4])
fig.update_xaxes(showgrid=True, ticks="outside")
fig.show()
```

### Section 3: Using open source data to find interesting trends

Find a dataset that is interesting and seems like it has at least 3 columns that would be easy to graph. Many United States government agencies publish data to the public (and you can even request data via a Freedom of Information Act.) Again, pick a dataset that seems graphable using the Plotly charts you've seen. While the entire text of Wikipedia is technically available data... that might be too much of a challege to be enjoyable to graph.

Boston's open data: https://data.boston.gov

Cambridge's open data: https://www.cambridgema.gov/departments/opendata

United States: https://data.gov

CDC: https://data.cdc.gov

Kaggle: https://www.kaggle.com/datasets

World Bank: https://data.worldbank.org

Five Thirty Eight: https://github.com/fivethirtyeight/data

#### Download the dataset to your computer and then load the dataset into Google Colab. This can be tricky especially with different browsers and size limits. LMK if you get stuck here and we will troubleshoot the issue.

#### Explore the dataframe using the pandas min, max, mean, and other statistical methods. What do you discover?

#### Create a graph using this data.

#### Are any variables that might be a proxy variables for a variable that is not in the data set?


